version: "2"
services:
  influx:
    image: influxdb:1.8.10
    container_name: influx
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
volumes:
  storage:
    external: false
