version: "3.3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - TZ=USA/Eastern
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-xyz # https://plex.tv/claim
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /home/joseph/plex/data/config:/config
      - /home/joseph/plex/data/tvshows:/tvshows
      - /home/joseph/plex/data/movies:/movies
      - /home/joseph/plex/data/music:/music
    restart: always
