version: "2"
services:
  boinc:
    image: boinc/client
    container_name: boinc
    restart: always
    volumes:
      - boinc-volume:/var/lib/boinc-client
    ports:
      - "31416:31416"
    environment:
      - BOINC_GUI_RPC_PASSWORD=hellothere
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
volumes:
  boinc-volume:
    external: false

# https://hub.docker.com/r/boinc/client/