version: "2"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    volumes:
      - mssql-storage:/var/lib/mssql
volumes:
  mssql-storage:
