version: '3.4'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    environment:
      USER: "joseph;mypassword"
      SHARE: "mysharename;/mnt;yes;no;no;joseph;joseph;joseph;'my awesome share'"
      TZ: "America/Eastern"
      NMBD: "true"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    volumes:
      - /home/joseph/docker/samba/data:/mnt  