version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.10.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Eastern'
      WEBPASSWORD: 'password' # TODO: Set password.
    volumes:
      - '/home/joseph/docker/pihole/etc-pihole/:/etc/pihole/'
      - '/home/joseph/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
