version: "3.3"
services:
  foldingathome:
    image: linuxserver/foldingathome:7.6.21
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=USA/Eastern
    ports:
      - "7396:7396"
    volumes:
      - folding:/config
    restart: unless-stopped
volumes:
  folding:
    external: false
